version: '3'
services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "9000:9000"
  msstore-microservice:
    build: ./msstore-microservice
    ports:
      - "9002:9002"
    links: 
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:9000/eureka
  csstore-microservice:
    build: ./csstore-microservice
    ports:
      - "9001:9001"
    links: 
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:9000/eureka


