spring:
  application:
    name: sidecar

server:
  port: 9004

       
eureka:
  client:
    serviceUrl:      
       defaultZone: http://localhost:9000/eureka
    register-with-eureka: true
    fetch-registry: true

sidecar:
  port: 3005
  health-uri: http://localhost:3005/health
    